apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
  labels:
    app: APP_LABEL_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP_LABEL_PLACEHOLDER
  template:
    metadata:
      labels:
        app: APP_LABEL_PLACEHOLDER
    spec:
      containers:
        - name: CONTAINER_NAME_PLACEHOLDER
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: CONTAINER_PORT_PLACEHOLDER
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME_PLACEHOLDER
spec:
  selector:
    app: APP_LABEL_PLACEHOLDER
  ports:
    - protocol: TCP
      port: SERVICE_PORT_PLACEHOLDER
      targetPort: CONTAINER_PORT_PLACEHOLDER
  type: LoadBalancer