replicaCount: 2
image:
  tag: "staging"
resources:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "400m"
    memory: "400Mi"
authDb:
  deployment:
    image: "postgres:11-alpine"
  pvc:
    size: "10Gi"
