apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: st-server
build:
  tagPolicy:
    sha256: { }
  artifacts:
    - image: st-auth-svc
      context: .
      docker:
        dockerfile: src/st-auth-svc/Dockerfile
        buildArgs:
          PORT: "50051"
          DB_URL: "postgres://root:StratTrad3r@auth-db:5432/auth_db?sslmode=disable"
          JWT_SECRET_KEY: "stauth983"
      sync:
        infer:
          - '**/*'
    - image: st-journal-svc
      context: .
      docker:
        dockerfile: src/st-journal-svc/Dockerfile
        buildArgs:
          PORT: "50052"
          DB_URL: "postgres://root:StratTrad3r@journal-db:5433/journal_db?sslmode=disable"
      sync:
        infer:
          - '**/*'
    - image: st-gateway
      context: .
      docker:
        dockerfile: src/st-gateway/Dockerfile
        buildArgs:
          API_VERSION: "1"
          AUTH_SVC_URL: "st-auth-svc:50051"
          JOURNAL_SVC_URL: "st-journal-svc:50052"
          JWT_SECRET_KEY: "stauth983"
          PORT: "8080"
      sync:
        infer:
          - '**/*'
deploy:
  helm:
    releases:
      - name: st-auth-svc
        chartPath: k8s/charts/st-auth-svc
        valuesFiles:
          - k8s/charts/st-auth-svc/values.yaml
        setValues:
          image.repository: st-auth-svc
          image.tag: latest
          service.port: 50051
          env:
            DB_URL: postgres://root:StratTrad3r@auth-db:5432/auth_db?sslmode=disable
            JWT_SECRET_KEY: stauth983
      - name: st-journal-svc
        chartPath: k8s/charts/st-journal-svc
        valuesFiles:
          - k8s/charts/st-journal-svc/values.yaml
        setValues:
          image.repository: st-journal-svc
          image.tag: latest
          service.port: 50052
          env:
            DB_URL: postgres://root:StratTrad3r@journal-db:5433/journal_db?sslmode=disable
      - name: st-gateway
        chartPath: k8s/charts/st-gateway
        valuesFiles:
          - k8s/charts/st-gateway/values.yaml
        setValues:
          image.repository: st-gateway
          image.tag: latest
          service.port: 8080
          env:
            API_VERSION: "1"
            AUTH_SVC_URL: st-auth-svc:50051
            JOURNAL_SVC_URL: st-journal-svc:50052
            JWT_SECRET_KEY: stauth983
portForward:
  - resourceType: service
    resourceName: st-auth-svc
    namespace: default
    port: 50051
    localPort: 50051
  - resourceType: service
    resourceName: st-journal-svc
    namespace: default
    port: 50052
    localPort: 50052
  - resourceType: service
    resourceName: st-gateway
    namespace: default
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: st-prometheus-server
    namespace: prometheus
    port: 80
    localPort: 9090
  - resourceType: service
    resourceName: st-auth-svc
    namespace: default
    port: 9093
    localPort: 9093
  - resourceType: service
    resourceName: st-journal-svc
    namespace: default
    port: 9092
    localPort: 9092
  - resourceType: service
    resourceName: grafana
    namespace: grafana
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: auth-db
    namespace: default
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: journal-db
    namespace: default
    port: 5433
    localPort: 5433
