replicaCount: 1
image:
  tag: "dev"
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"
authDb:
  deployment:
    image: "postgres:alpine"
  pvc:
    size: "1Gi"
