apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app.label }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: metrics
      port:  {{ .Values.service.metricsPort }}
      targetPort:  {{ .Values.service.metricsPort }}
  type: LoadBalancer
