apiVersion: apps/v1
kind: Deployment
metadata:
  name: st-auth-svc
  labels:
    app: st-auth-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: st-auth-svc
  template:
    metadata:
      labels:
        app: st-auth-svc
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9093'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - name: st-auth-svc
          image: st-auth-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
