apiVersion: v1
kind: Service
metadata:
  name: st-auth-svc
spec:
  selector:
    app: st-auth-svc
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 9093
      targetPort: 9093

  type: LoadBalancer
