apiVersion: apps/v1
kind: Deployment
metadata:
  name: st-gateway
  labels:
    app: st-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: st-gateway
  template:
    metadata:
      labels:
        app: st-gateway
    spec:
      containers:
        - name: st-gateway
          image: st-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
