apiVersion: v1
kind: Service
metadata:
  name: st-journal-svc
spec:
  selector:
    app: st-journal-svc
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
    - name: metrics
      port: 9092
      targetPort: 9092