// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/pb/journal.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateJournalRequest struct {
	Id                   uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartDate            *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Name                 *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description          *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	UsersSubscribed      []uint64                `protobuf:"varint,8,rep,packed,name=users_subscribed,json=usersSubscribed,proto3" json:"users_subscribed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateJournalRequest) Reset()         { *m = CreateJournalRequest{} }
func (m *CreateJournalRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJournalRequest) ProtoMessage()    {}
func (*CreateJournalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{0}
}
func (m *CreateJournalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJournalRequest.Unmarshal(m, b)
}
func (m *CreateJournalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJournalRequest.Marshal(b, m, deterministic)
}
func (m *CreateJournalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJournalRequest.Merge(m, src)
}
func (m *CreateJournalRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJournalRequest.Size(m)
}
func (m *CreateJournalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJournalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJournalRequest proto.InternalMessageInfo

func (m *CreateJournalRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateJournalRequest) GetCreatedBy() *wrapperspb.StringValue {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *CreateJournalRequest) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CreateJournalRequest) GetStartDate() *timestamppb.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *CreateJournalRequest) GetEndDate() *timestamppb.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *CreateJournalRequest) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *CreateJournalRequest) GetDescription() *wrapperspb.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *CreateJournalRequest) GetUsersSubscribed() []uint64 {
	if m != nil {
		return m.UsersSubscribed
	}
	return nil
}

type CreateJournalResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *Journal `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJournalResponse) Reset()         { *m = CreateJournalResponse{} }
func (m *CreateJournalResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJournalResponse) ProtoMessage()    {}
func (*CreateJournalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{1}
}
func (m *CreateJournalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJournalResponse.Unmarshal(m, b)
}
func (m *CreateJournalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJournalResponse.Marshal(b, m, deterministic)
}
func (m *CreateJournalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJournalResponse.Merge(m, src)
}
func (m *CreateJournalResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJournalResponse.Size(m)
}
func (m *CreateJournalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJournalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJournalResponse proto.InternalMessageInfo

func (m *CreateJournalResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateJournalResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateJournalResponse) GetData() *Journal {
	if m != nil {
		return m.Data
	}
	return nil
}

type EditJournalData struct {
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy            string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartDate            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Name                 string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	UsersSubscribed      []uint64               `protobuf:"varint,8,rep,packed,name=users_subscribed,json=usersSubscribed,proto3" json:"users_subscribed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EditJournalData) Reset()         { *m = EditJournalData{} }
func (m *EditJournalData) String() string { return proto.CompactTextString(m) }
func (*EditJournalData) ProtoMessage()    {}
func (*EditJournalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{2}
}
func (m *EditJournalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditJournalData.Unmarshal(m, b)
}
func (m *EditJournalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditJournalData.Marshal(b, m, deterministic)
}
func (m *EditJournalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditJournalData.Merge(m, src)
}
func (m *EditJournalData) XXX_Size() int {
	return xxx_messageInfo_EditJournalData.Size(m)
}
func (m *EditJournalData) XXX_DiscardUnknown() {
	xxx_messageInfo_EditJournalData.DiscardUnknown(m)
}

var xxx_messageInfo_EditJournalData proto.InternalMessageInfo

func (m *EditJournalData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditJournalData) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *EditJournalData) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *EditJournalData) GetStartDate() *timestamppb.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *EditJournalData) GetEndDate() *timestamppb.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *EditJournalData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditJournalData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditJournalData) GetUsersSubscribed() []uint64 {
	if m != nil {
		return m.UsersSubscribed
	}
	return nil
}

type EditJournalRequest struct {
	Id                   uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartDate            *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Name                 *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description          *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	UsersSubscribed      []uint64                `protobuf:"varint,8,rep,packed,name=users_subscribed,json=usersSubscribed,proto3" json:"users_subscribed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EditJournalRequest) Reset()         { *m = EditJournalRequest{} }
func (m *EditJournalRequest) String() string { return proto.CompactTextString(m) }
func (*EditJournalRequest) ProtoMessage()    {}
func (*EditJournalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{3}
}
func (m *EditJournalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditJournalRequest.Unmarshal(m, b)
}
func (m *EditJournalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditJournalRequest.Marshal(b, m, deterministic)
}
func (m *EditJournalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditJournalRequest.Merge(m, src)
}
func (m *EditJournalRequest) XXX_Size() int {
	return xxx_messageInfo_EditJournalRequest.Size(m)
}
func (m *EditJournalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditJournalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditJournalRequest proto.InternalMessageInfo

func (m *EditJournalRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditJournalRequest) GetCreatedBy() *wrapperspb.StringValue {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *EditJournalRequest) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *EditJournalRequest) GetStartDate() *timestamppb.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *EditJournalRequest) GetEndDate() *timestamppb.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *EditJournalRequest) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *EditJournalRequest) GetDescription() *wrapperspb.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *EditJournalRequest) GetUsersSubscribed() []uint64 {
	if m != nil {
		return m.UsersSubscribed
	}
	return nil
}

type EditJournalResponse struct {
	Status               uint64           `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *EditJournalData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EditJournalResponse) Reset()         { *m = EditJournalResponse{} }
func (m *EditJournalResponse) String() string { return proto.CompactTextString(m) }
func (*EditJournalResponse) ProtoMessage()    {}
func (*EditJournalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{4}
}
func (m *EditJournalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditJournalResponse.Unmarshal(m, b)
}
func (m *EditJournalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditJournalResponse.Marshal(b, m, deterministic)
}
func (m *EditJournalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditJournalResponse.Merge(m, src)
}
func (m *EditJournalResponse) XXX_Size() int {
	return xxx_messageInfo_EditJournalResponse.Size(m)
}
func (m *EditJournalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditJournalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditJournalResponse proto.InternalMessageInfo

func (m *EditJournalResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *EditJournalResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *EditJournalResponse) GetData() *EditJournalData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Journal struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy            string   `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"createdBy"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`
	StartDate            string   `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"startDate"`
	EndDate              string   `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"endDate"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	UsersSubscribed      []uint64 `protobuf:"varint,8,rep,packed,name=users_subscribed,json=usersSubscribed,proto3" json:"usersSubscribed"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Journal) Reset()         { *m = Journal{} }
func (m *Journal) String() string { return proto.CompactTextString(m) }
func (*Journal) ProtoMessage()    {}
func (*Journal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{5}
}
func (m *Journal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Journal.Unmarshal(m, b)
}
func (m *Journal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Journal.Marshal(b, m, deterministic)
}
func (m *Journal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Journal.Merge(m, src)
}
func (m *Journal) XXX_Size() int {
	return xxx_messageInfo_Journal.Size(m)
}
func (m *Journal) XXX_DiscardUnknown() {
	xxx_messageInfo_Journal.DiscardUnknown(m)
}

var xxx_messageInfo_Journal proto.InternalMessageInfo

func (m *Journal) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Journal) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Journal) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Journal) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Journal) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Journal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Journal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Journal) GetUsersSubscribed() []uint64 {
	if m != nil {
		return m.UsersSubscribed
	}
	return nil
}

type FindAllJournalsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllJournalsRequest) Reset()         { *m = FindAllJournalsRequest{} }
func (m *FindAllJournalsRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllJournalsRequest) ProtoMessage()    {}
func (*FindAllJournalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{6}
}
func (m *FindAllJournalsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllJournalsRequest.Unmarshal(m, b)
}
func (m *FindAllJournalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllJournalsRequest.Marshal(b, m, deterministic)
}
func (m *FindAllJournalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllJournalsRequest.Merge(m, src)
}
func (m *FindAllJournalsRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllJournalsRequest.Size(m)
}
func (m *FindAllJournalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllJournalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllJournalsRequest proto.InternalMessageInfo

type FindAllJournalsResponse struct {
	Status               uint64     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*Journal `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindAllJournalsResponse) Reset()         { *m = FindAllJournalsResponse{} }
func (m *FindAllJournalsResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllJournalsResponse) ProtoMessage()    {}
func (*FindAllJournalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{7}
}
func (m *FindAllJournalsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllJournalsResponse.Unmarshal(m, b)
}
func (m *FindAllJournalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllJournalsResponse.Marshal(b, m, deterministic)
}
func (m *FindAllJournalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllJournalsResponse.Merge(m, src)
}
func (m *FindAllJournalsResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllJournalsResponse.Size(m)
}
func (m *FindAllJournalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllJournalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllJournalsResponse proto.InternalMessageInfo

func (m *FindAllJournalsResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FindAllJournalsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FindAllJournalsResponse) GetData() []*Journal {
	if m != nil {
		return m.Data
	}
	return nil
}

type FindOneJournalRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneJournalRequest) Reset()         { *m = FindOneJournalRequest{} }
func (m *FindOneJournalRequest) String() string { return proto.CompactTextString(m) }
func (*FindOneJournalRequest) ProtoMessage()    {}
func (*FindOneJournalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{8}
}
func (m *FindOneJournalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneJournalRequest.Unmarshal(m, b)
}
func (m *FindOneJournalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneJournalRequest.Marshal(b, m, deterministic)
}
func (m *FindOneJournalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneJournalRequest.Merge(m, src)
}
func (m *FindOneJournalRequest) XXX_Size() int {
	return xxx_messageInfo_FindOneJournalRequest.Size(m)
}
func (m *FindOneJournalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneJournalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneJournalRequest proto.InternalMessageInfo

func (m *FindOneJournalRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindOneJournalResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *Journal `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneJournalResponse) Reset()         { *m = FindOneJournalResponse{} }
func (m *FindOneJournalResponse) String() string { return proto.CompactTextString(m) }
func (*FindOneJournalResponse) ProtoMessage()    {}
func (*FindOneJournalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{9}
}
func (m *FindOneJournalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneJournalResponse.Unmarshal(m, b)
}
func (m *FindOneJournalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneJournalResponse.Marshal(b, m, deterministic)
}
func (m *FindOneJournalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneJournalResponse.Merge(m, src)
}
func (m *FindOneJournalResponse) XXX_Size() int {
	return xxx_messageInfo_FindOneJournalResponse.Size(m)
}
func (m *FindOneJournalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneJournalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneJournalResponse proto.InternalMessageInfo

func (m *FindOneJournalResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FindOneJournalResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FindOneJournalResponse) GetData() *Journal {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteJournalRequest struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJournalRequest) Reset()         { *m = DeleteJournalRequest{} }
func (m *DeleteJournalRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJournalRequest) ProtoMessage()    {}
func (*DeleteJournalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{10}
}
func (m *DeleteJournalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJournalRequest.Unmarshal(m, b)
}
func (m *DeleteJournalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJournalRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJournalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJournalRequest.Merge(m, src)
}
func (m *DeleteJournalRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJournalRequest.Size(m)
}
func (m *DeleteJournalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJournalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJournalRequest proto.InternalMessageInfo

func (m *DeleteJournalRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteJournalResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJournalResponse) Reset()         { *m = DeleteJournalResponse{} }
func (m *DeleteJournalResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteJournalResponse) ProtoMessage()    {}
func (*DeleteJournalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{11}
}
func (m *DeleteJournalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJournalResponse.Unmarshal(m, b)
}
func (m *DeleteJournalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJournalResponse.Marshal(b, m, deterministic)
}
func (m *DeleteJournalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJournalResponse.Merge(m, src)
}
func (m *DeleteJournalResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteJournalResponse.Size(m)
}
func (m *DeleteJournalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJournalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJournalResponse proto.InternalMessageInfo

func (m *DeleteJournalResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteJournalResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateTradeRequest struct {
	TimeExecuted         *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=time_executed,json=timeExecuted,proto3" json:"time_executed,omitempty"`
	Market               *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=market,proto3" json:"market,omitempty"`
	StopLoss             *wrapperspb.FloatValue  `protobuf:"bytes,4,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	EntryPrice           *wrapperspb.FloatValue  `protobuf:"bytes,5,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	ExitPrice            *wrapperspb.FloatValue  `protobuf:"bytes,6,opt,name=exit_price,json=exitPrice,proto3" json:"exit_price,omitempty"`
	Journal              uint64                  `protobuf:"varint,7,opt,name=journal,proto3" json:"journal,omitempty"`
	Quantity             *wrapperspb.FloatValue  `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Outcome              *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Direction            *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=direction,proto3" json:"direction,omitempty"`
	BaseInstrument       *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=base_instrument,json=baseInstrument,proto3" json:"base_instrument,omitempty"`
	QuoteInstrument      *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=quote_instrument,json=quoteInstrument,proto3" json:"quote_instrument,omitempty"`
	TakeProfit           *wrapperspb.FloatValue  `protobuf:"bytes,13,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	Comments             *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=comments,proto3" json:"comments,omitempty"`
	Strategy             *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=strategy,proto3" json:"strategy,omitempty"`
	TimeClosed           *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=time_closed,json=timeClosed,proto3" json:"time_closed,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateTradeRequest) Reset()         { *m = CreateTradeRequest{} }
func (m *CreateTradeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTradeRequest) ProtoMessage()    {}
func (*CreateTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{12}
}
func (m *CreateTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTradeRequest.Unmarshal(m, b)
}
func (m *CreateTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTradeRequest.Marshal(b, m, deterministic)
}
func (m *CreateTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTradeRequest.Merge(m, src)
}
func (m *CreateTradeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTradeRequest.Size(m)
}
func (m *CreateTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTradeRequest proto.InternalMessageInfo

func (m *CreateTradeRequest) GetTimeExecuted() *timestamppb.Timestamp {
	if m != nil {
		return m.TimeExecuted
	}
	return nil
}

func (m *CreateTradeRequest) GetMarket() *wrapperspb.StringValue {
	if m != nil {
		return m.Market
	}
	return nil
}

func (m *CreateTradeRequest) GetStopLoss() *wrapperspb.FloatValue {
	if m != nil {
		return m.StopLoss
	}
	return nil
}

func (m *CreateTradeRequest) GetEntryPrice() *wrapperspb.FloatValue {
	if m != nil {
		return m.EntryPrice
	}
	return nil
}

func (m *CreateTradeRequest) GetExitPrice() *wrapperspb.FloatValue {
	if m != nil {
		return m.ExitPrice
	}
	return nil
}

func (m *CreateTradeRequest) GetJournal() uint64 {
	if m != nil {
		return m.Journal
	}
	return 0
}

func (m *CreateTradeRequest) GetQuantity() *wrapperspb.FloatValue {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *CreateTradeRequest) GetOutcome() *wrapperspb.StringValue {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *CreateTradeRequest) GetDirection() *wrapperspb.StringValue {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *CreateTradeRequest) GetBaseInstrument() *wrapperspb.StringValue {
	if m != nil {
		return m.BaseInstrument
	}
	return nil
}

func (m *CreateTradeRequest) GetQuoteInstrument() *wrapperspb.StringValue {
	if m != nil {
		return m.QuoteInstrument
	}
	return nil
}

func (m *CreateTradeRequest) GetTakeProfit() *wrapperspb.FloatValue {
	if m != nil {
		return m.TakeProfit
	}
	return nil
}

func (m *CreateTradeRequest) GetComments() *wrapperspb.StringValue {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *CreateTradeRequest) GetStrategy() *wrapperspb.StringValue {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (m *CreateTradeRequest) GetTimeClosed() *timestamppb.Timestamp {
	if m != nil {
		return m.TimeClosed
	}
	return nil
}

func (m *CreateTradeRequest) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateTradeResponse struct {
	Status               uint64     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *TradeData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateTradeResponse) Reset()         { *m = CreateTradeResponse{} }
func (m *CreateTradeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTradeResponse) ProtoMessage()    {}
func (*CreateTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{13}
}
func (m *CreateTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTradeResponse.Unmarshal(m, b)
}
func (m *CreateTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTradeResponse.Marshal(b, m, deterministic)
}
func (m *CreateTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTradeResponse.Merge(m, src)
}
func (m *CreateTradeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTradeResponse.Size(m)
}
func (m *CreateTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTradeResponse proto.InternalMessageInfo

func (m *CreateTradeResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateTradeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateTradeResponse) GetData() *TradeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TradeData struct {
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeExecuted         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_executed,json=timeExecuted,proto3" json:"time_executed,omitempty"`
	Market               string                 `protobuf:"bytes,3,opt,name=market,proto3" json:"market,omitempty"`
	StopLoss             float32                `protobuf:"fixed32,4,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	EntryPrice           float32                `protobuf:"fixed32,5,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	ExitPrice            float32                `protobuf:"fixed32,6,opt,name=exit_price,json=exitPrice,proto3" json:"exit_price,omitempty"`
	Journal              uint64                 `protobuf:"varint,7,opt,name=journal,proto3" json:"journal,omitempty"`
	Quantity             float32                `protobuf:"fixed32,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Outcome              string                 `protobuf:"bytes,9,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Direction            string                 `protobuf:"bytes,10,opt,name=direction,proto3" json:"direction,omitempty"`
	BaseInstrument       string                 `protobuf:"bytes,11,opt,name=base_instrument,json=baseInstrument,proto3" json:"base_instrument,omitempty"`
	QuoteInstrument      string                 `protobuf:"bytes,12,opt,name=quote_instrument,json=quoteInstrument,proto3" json:"quote_instrument,omitempty"`
	TakeProfit           float32                `protobuf:"fixed32,13,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	Comments             string                 `protobuf:"bytes,14,opt,name=comments,proto3" json:"comments,omitempty"`
	Strategy             string                 `protobuf:"bytes,15,opt,name=strategy,proto3" json:"strategy,omitempty"`
	TimeClosed           *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=time_closed,json=timeClosed,proto3" json:"time_closed,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TradeData) Reset()         { *m = TradeData{} }
func (m *TradeData) String() string { return proto.CompactTextString(m) }
func (*TradeData) ProtoMessage()    {}
func (*TradeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{14}
}
func (m *TradeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeData.Unmarshal(m, b)
}
func (m *TradeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeData.Marshal(b, m, deterministic)
}
func (m *TradeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeData.Merge(m, src)
}
func (m *TradeData) XXX_Size() int {
	return xxx_messageInfo_TradeData.Size(m)
}
func (m *TradeData) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeData.DiscardUnknown(m)
}

var xxx_messageInfo_TradeData proto.InternalMessageInfo

func (m *TradeData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TradeData) GetTimeExecuted() *timestamppb.Timestamp {
	if m != nil {
		return m.TimeExecuted
	}
	return nil
}

func (m *TradeData) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *TradeData) GetStopLoss() float32 {
	if m != nil {
		return m.StopLoss
	}
	return 0
}

func (m *TradeData) GetEntryPrice() float32 {
	if m != nil {
		return m.EntryPrice
	}
	return 0
}

func (m *TradeData) GetExitPrice() float32 {
	if m != nil {
		return m.ExitPrice
	}
	return 0
}

func (m *TradeData) GetJournal() uint64 {
	if m != nil {
		return m.Journal
	}
	return 0
}

func (m *TradeData) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *TradeData) GetOutcome() string {
	if m != nil {
		return m.Outcome
	}
	return ""
}

func (m *TradeData) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *TradeData) GetBaseInstrument() string {
	if m != nil {
		return m.BaseInstrument
	}
	return ""
}

func (m *TradeData) GetQuoteInstrument() string {
	if m != nil {
		return m.QuoteInstrument
	}
	return ""
}

func (m *TradeData) GetTakeProfit() float32 {
	if m != nil {
		return m.TakeProfit
	}
	return 0
}

func (m *TradeData) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *TradeData) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *TradeData) GetTimeClosed() *timestamppb.Timestamp {
	if m != nil {
		return m.TimeClosed
	}
	return nil
}

func (m *TradeData) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type EditTradeRequest struct {
	Id                   uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeExecuted         *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=time_executed,json=timeExecuted,proto3" json:"time_executed,omitempty"`
	Market               *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=market,proto3" json:"market,omitempty"`
	StopLoss             *wrapperspb.FloatValue  `protobuf:"bytes,4,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	EntryPrice           *wrapperspb.FloatValue  `protobuf:"bytes,5,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	ExitPrice            *wrapperspb.FloatValue  `protobuf:"bytes,6,opt,name=exit_price,json=exitPrice,proto3" json:"exit_price,omitempty"`
	Journal              uint64                  `protobuf:"varint,7,opt,name=journal,proto3" json:"journal,omitempty"`
	Quantity             *wrapperspb.FloatValue  `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Outcome              *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Direction            *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=direction,proto3" json:"direction,omitempty"`
	BaseInstrument       *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=base_instrument,json=baseInstrument,proto3" json:"base_instrument,omitempty"`
	QuoteInstrument      *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=quote_instrument,json=quoteInstrument,proto3" json:"quote_instrument,omitempty"`
	TakeProfit           *wrapperspb.FloatValue  `protobuf:"bytes,13,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	Comments             *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=comments,proto3" json:"comments,omitempty"`
	Strategy             *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=strategy,proto3" json:"strategy,omitempty"`
	TimeClosed           *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=time_closed,json=timeClosed,proto3" json:"time_closed,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EditTradeRequest) Reset()         { *m = EditTradeRequest{} }
func (m *EditTradeRequest) String() string { return proto.CompactTextString(m) }
func (*EditTradeRequest) ProtoMessage()    {}
func (*EditTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{15}
}
func (m *EditTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditTradeRequest.Unmarshal(m, b)
}
func (m *EditTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditTradeRequest.Marshal(b, m, deterministic)
}
func (m *EditTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditTradeRequest.Merge(m, src)
}
func (m *EditTradeRequest) XXX_Size() int {
	return xxx_messageInfo_EditTradeRequest.Size(m)
}
func (m *EditTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditTradeRequest proto.InternalMessageInfo

func (m *EditTradeRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditTradeRequest) GetTimeExecuted() *timestamppb.Timestamp {
	if m != nil {
		return m.TimeExecuted
	}
	return nil
}

func (m *EditTradeRequest) GetMarket() *wrapperspb.StringValue {
	if m != nil {
		return m.Market
	}
	return nil
}

func (m *EditTradeRequest) GetStopLoss() *wrapperspb.FloatValue {
	if m != nil {
		return m.StopLoss
	}
	return nil
}

func (m *EditTradeRequest) GetEntryPrice() *wrapperspb.FloatValue {
	if m != nil {
		return m.EntryPrice
	}
	return nil
}

func (m *EditTradeRequest) GetExitPrice() *wrapperspb.FloatValue {
	if m != nil {
		return m.ExitPrice
	}
	return nil
}

func (m *EditTradeRequest) GetJournal() uint64 {
	if m != nil {
		return m.Journal
	}
	return 0
}

func (m *EditTradeRequest) GetQuantity() *wrapperspb.FloatValue {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *EditTradeRequest) GetOutcome() *wrapperspb.StringValue {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *EditTradeRequest) GetDirection() *wrapperspb.StringValue {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *EditTradeRequest) GetBaseInstrument() *wrapperspb.StringValue {
	if m != nil {
		return m.BaseInstrument
	}
	return nil
}

func (m *EditTradeRequest) GetQuoteInstrument() *wrapperspb.StringValue {
	if m != nil {
		return m.QuoteInstrument
	}
	return nil
}

func (m *EditTradeRequest) GetTakeProfit() *wrapperspb.FloatValue {
	if m != nil {
		return m.TakeProfit
	}
	return nil
}

func (m *EditTradeRequest) GetComments() *wrapperspb.StringValue {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *EditTradeRequest) GetStrategy() *wrapperspb.StringValue {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (m *EditTradeRequest) GetTimeClosed() *timestamppb.Timestamp {
	if m != nil {
		return m.TimeClosed
	}
	return nil
}

func (m *EditTradeRequest) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type EditTradeResponse struct {
	Status               uint64     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *TradeData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EditTradeResponse) Reset()         { *m = EditTradeResponse{} }
func (m *EditTradeResponse) String() string { return proto.CompactTextString(m) }
func (*EditTradeResponse) ProtoMessage()    {}
func (*EditTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{16}
}
func (m *EditTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditTradeResponse.Unmarshal(m, b)
}
func (m *EditTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditTradeResponse.Marshal(b, m, deterministic)
}
func (m *EditTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditTradeResponse.Merge(m, src)
}
func (m *EditTradeResponse) XXX_Size() int {
	return xxx_messageInfo_EditTradeResponse.Size(m)
}
func (m *EditTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditTradeResponse proto.InternalMessageInfo

func (m *EditTradeResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *EditTradeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *EditTradeResponse) GetData() *TradeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type FindOneTradeRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneTradeRequest) Reset()         { *m = FindOneTradeRequest{} }
func (m *FindOneTradeRequest) String() string { return proto.CompactTextString(m) }
func (*FindOneTradeRequest) ProtoMessage()    {}
func (*FindOneTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{17}
}
func (m *FindOneTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneTradeRequest.Unmarshal(m, b)
}
func (m *FindOneTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneTradeRequest.Marshal(b, m, deterministic)
}
func (m *FindOneTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneTradeRequest.Merge(m, src)
}
func (m *FindOneTradeRequest) XXX_Size() int {
	return xxx_messageInfo_FindOneTradeRequest.Size(m)
}
func (m *FindOneTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneTradeRequest proto.InternalMessageInfo

func (m *FindOneTradeRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindOneTradeResponse struct {
	Status               uint64     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *TradeData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindOneTradeResponse) Reset()         { *m = FindOneTradeResponse{} }
func (m *FindOneTradeResponse) String() string { return proto.CompactTextString(m) }
func (*FindOneTradeResponse) ProtoMessage()    {}
func (*FindOneTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{18}
}
func (m *FindOneTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneTradeResponse.Unmarshal(m, b)
}
func (m *FindOneTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneTradeResponse.Marshal(b, m, deterministic)
}
func (m *FindOneTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneTradeResponse.Merge(m, src)
}
func (m *FindOneTradeResponse) XXX_Size() int {
	return xxx_messageInfo_FindOneTradeResponse.Size(m)
}
func (m *FindOneTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneTradeResponse proto.InternalMessageInfo

func (m *FindOneTradeResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FindOneTradeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FindOneTradeResponse) GetData() *TradeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteTradeRequest struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTradeRequest) Reset()         { *m = DeleteTradeRequest{} }
func (m *DeleteTradeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTradeRequest) ProtoMessage()    {}
func (*DeleteTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{19}
}
func (m *DeleteTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTradeRequest.Unmarshal(m, b)
}
func (m *DeleteTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTradeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTradeRequest.Merge(m, src)
}
func (m *DeleteTradeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTradeRequest.Size(m)
}
func (m *DeleteTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTradeRequest proto.InternalMessageInfo

func (m *DeleteTradeRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteTradeResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTradeResponse) Reset()         { *m = DeleteTradeResponse{} }
func (m *DeleteTradeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTradeResponse) ProtoMessage()    {}
func (*DeleteTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c171b4ba7d2d024e, []int{20}
}
func (m *DeleteTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTradeResponse.Unmarshal(m, b)
}
func (m *DeleteTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTradeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTradeResponse.Merge(m, src)
}
func (m *DeleteTradeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTradeResponse.Size(m)
}
func (m *DeleteTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTradeResponse proto.InternalMessageInfo

func (m *DeleteTradeResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteTradeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateJournalRequest)(nil), "journal.CreateJournalRequest")
	proto.RegisterType((*CreateJournalResponse)(nil), "journal.CreateJournalResponse")
	proto.RegisterType((*EditJournalData)(nil), "journal.EditJournalData")
	proto.RegisterType((*EditJournalRequest)(nil), "journal.EditJournalRequest")
	proto.RegisterType((*EditJournalResponse)(nil), "journal.EditJournalResponse")
	proto.RegisterType((*Journal)(nil), "journal.Journal")
	proto.RegisterType((*FindAllJournalsRequest)(nil), "journal.FindAllJournalsRequest")
	proto.RegisterType((*FindAllJournalsResponse)(nil), "journal.FindAllJournalsResponse")
	proto.RegisterType((*FindOneJournalRequest)(nil), "journal.FindOneJournalRequest")
	proto.RegisterType((*FindOneJournalResponse)(nil), "journal.FindOneJournalResponse")
	proto.RegisterType((*DeleteJournalRequest)(nil), "journal.DeleteJournalRequest")
	proto.RegisterType((*DeleteJournalResponse)(nil), "journal.DeleteJournalResponse")
	proto.RegisterType((*CreateTradeRequest)(nil), "journal.CreateTradeRequest")
	proto.RegisterType((*CreateTradeResponse)(nil), "journal.CreateTradeResponse")
	proto.RegisterType((*TradeData)(nil), "journal.TradeData")
	proto.RegisterType((*EditTradeRequest)(nil), "journal.EditTradeRequest")
	proto.RegisterType((*EditTradeResponse)(nil), "journal.EditTradeResponse")
	proto.RegisterType((*FindOneTradeRequest)(nil), "journal.FindOneTradeRequest")
	proto.RegisterType((*FindOneTradeResponse)(nil), "journal.FindOneTradeResponse")
	proto.RegisterType((*DeleteTradeRequest)(nil), "journal.DeleteTradeRequest")
	proto.RegisterType((*DeleteTradeResponse)(nil), "journal.DeleteTradeResponse")
}

func init() { proto.RegisterFile("pkg/pb/journal.proto", fileDescriptor_c171b4ba7d2d024e) }

var fileDescriptor_c171b4ba7d2d024e = []byte{
	// 1230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x55, 0x24, 0xc5, 0x12, 0xaf, 0x6c, 0xcb, 0x19, 0x3f, 0xca, 0xca, 0xb6, 0x64, 0x10, 0xa9,
	0xe3, 0x00, 0xae, 0x54, 0xa4, 0xaf, 0x34, 0x09, 0x52, 0xf8, 0x95, 0xa2, 0x41, 0x8b, 0x1a, 0x72,
	0x90, 0x45, 0x37, 0xc2, 0x48, 0x9c, 0xa8, 0xac, 0x29, 0x92, 0x9e, 0x19, 0xb6, 0xf1, 0x9f, 0xf4,
	0x1f, 0x8a, 0xfe, 0x43, 0xbb, 0xcb, 0x2a, 0xe8, 0xba, 0x0b, 0xa3, 0x70, 0xba, 0xf2, 0x57, 0x14,
	0x1c, 0x3e, 0x3c, 0x7c, 0xc8, 0x66, 0xed, 0xba, 0x48, 0x01, 0xef, 0xc4, 0x99, 0x73, 0x2e, 0x67,
	0x78, 0xe6, 0xdc, 0x3b, 0x57, 0x30, 0xe7, 0xec, 0x0f, 0x3b, 0x4e, 0xbf, 0xf3, 0xbd, 0xed, 0x52,
	0x0b, 0x9b, 0x6d, 0x87, 0xda, 0xdc, 0x46, 0x95, 0xe0, 0xb1, 0xd1, 0x1a, 0xda, 0xf6, 0xd0, 0x24,
	0x1d, 0x31, 0xdc, 0x77, 0x5f, 0x74, 0xb8, 0x31, 0x22, 0x8c, 0xe3, 0x91, 0xe3, 0x23, 0x1b, 0xcd,
	0x24, 0xe0, 0x47, 0x8a, 0x1d, 0x87, 0x50, 0x16, 0xcc, 0xbf, 0x3f, 0x34, 0xf8, 0x77, 0x6e, 0xbf,
	0x3d, 0xb0, 0x47, 0x9d, 0xa1, 0x3d, 0xb4, 0x4f, 0x81, 0xde, 0x93, 0x78, 0x10, 0xbf, 0x7c, 0xb8,
	0xf6, 0x4b, 0x09, 0xe6, 0xb6, 0x28, 0xc1, 0x9c, 0x3c, 0xf5, 0x57, 0xd0, 0x25, 0x07, 0x2e, 0x61,
	0x1c, 0x4d, 0x43, 0xd1, 0xd0, 0xd5, 0x1b, 0x2b, 0x37, 0xd6, 0xca, 0xdd, 0xa2, 0xa1, 0xa3, 0x87,
	0x00, 0x03, 0x81, 0xd3, 0x7b, 0xfd, 0x43, 0xb5, 0xb8, 0x72, 0x63, 0xad, 0x76, 0x6f, 0xa9, 0xed,
	0x2f, 0xa6, 0x1d, 0xbe, 0xa3, 0xbd, 0xc7, 0xa9, 0x61, 0x0d, 0x9f, 0x63, 0xd3, 0x25, 0x5d, 0x25,
	0xc0, 0x6f, 0x1e, 0xa2, 0xcf, 0x4e, 0xc9, 0x98, 0xab, 0x25, 0x41, 0x6e, 0xa4, 0xc8, 0xcf, 0xc2,
	0xad, 0x46, 0xd4, 0x0d, 0xee, 0x51, 0x19, 0xc7, 0x94, 0xf7, 0x74, 0xcc, 0x89, 0x5a, 0x3e, 0x9f,
	0x2a, 0xd0, 0xdb, 0x98, 0x13, 0xf4, 0x31, 0x54, 0x89, 0xa5, 0xfb, 0xc4, 0x9b, 0xe7, 0x12, 0x2b,
	0xc4, 0xd2, 0x05, 0xed, 0x03, 0x28, 0x5b, 0x78, 0x44, 0xd4, 0x89, 0x1c, 0x7b, 0x14, 0x48, 0xf4,
	0x18, 0x6a, 0x3a, 0x61, 0x03, 0x6a, 0x38, 0xdc, 0xb0, 0x2d, 0xb5, 0x92, 0x83, 0x28, 0x13, 0xd0,
	0x5d, 0x98, 0x71, 0x19, 0xa1, 0xac, 0xc7, 0xdc, 0xbe, 0x37, 0xda, 0x27, 0xba, 0x5a, 0x5d, 0x29,
	0xad, 0x95, 0xbb, 0x75, 0x31, 0xbe, 0x17, 0x0d, 0x6b, 0xfb, 0x30, 0x9f, 0x90, 0x8b, 0x39, 0xb6,
	0xc5, 0x08, 0x5a, 0x80, 0x09, 0xc6, 0x31, 0x77, 0x59, 0xa0, 0x59, 0xf0, 0x84, 0xe6, 0xe0, 0x26,
	0xa1, 0xd4, 0xa6, 0x42, 0x32, 0xa5, 0xeb, 0x3f, 0xa0, 0xdb, 0x50, 0xd6, 0x31, 0xc7, 0x81, 0x14,
	0x33, 0xed, 0xf0, 0x34, 0x86, 0x51, 0xc5, 0xac, 0xf6, 0xba, 0x08, 0xf5, 0x1d, 0xdd, 0xe0, 0xc1,
	0xe8, 0x36, 0xe6, 0x38, 0x75, 0x2e, 0x96, 0x53, 0xe7, 0x42, 0xf9, 0xdf, 0x2a, 0x8f, 0x24, 0xe5,
	0x95, 0x40, 0xdb, 0x95, 0xb4, 0xb6, 0xca, 0x85, 0xd5, 0xfb, 0xb9, 0x04, 0x48, 0xfa, 0xa0, 0xd7,
	0x5e, 0x7b, 0xab, 0xbd, 0x76, 0x00, 0xb3, 0x31, 0xb1, 0x2e, 0xe4, 0xb4, 0xf5, 0x98, 0xd3, 0xd4,
	0xc8, 0x69, 0x09, 0x5f, 0x05, 0x8e, 0xfb, 0xad, 0x08, 0x95, 0x60, 0x34, 0x75, 0x2a, 0xd6, 0xd3,
	0x4e, 0xdb, 0x9c, 0x3a, 0x39, 0x6a, 0x9d, 0x6a, 0x2f, 0x1f, 0x83, 0xf5, 0xd4, 0x31, 0x88, 0xa3,
	0x37, 0xb8, 0xac, 0xfc, 0x7a, 0x4a, 0xf9, 0x00, 0x1d, 0x29, 0x2c, 0x8b, 0xbd, 0x9a, 0x10, 0x5b,
	0xd9, 0xac, 0x9d, 0x1c, 0xb5, 0x42, 0x51, 0x2f, 0xeb, 0xa7, 0xc7, 0xe3, 0x14, 0xda, 0x9c, 0x3d,
	0x39, 0x6a, 0x25, 0x55, 0x4a, 0xcb, 0xa6, 0xc2, 0xc2, 0x13, 0xc3, 0xd2, 0x37, 0x4c, 0x33, 0xf8,
	0x92, 0x2c, 0xf0, 0x99, 0x36, 0x82, 0x77, 0x52, 0x33, 0x97, 0x4c, 0x9f, 0xa5, 0x33, 0xd2, 0xe7,
	0x1d, 0x98, 0xf7, 0x5e, 0xf7, 0x8d, 0x75, 0x4e, 0x6d, 0xd5, 0x4c, 0x7f, 0xc5, 0x32, 0xf0, 0x0a,
	0xb3, 0xfa, 0x2a, 0xcc, 0x6d, 0x13, 0x93, 0x8c, 0xad, 0xf8, 0xa5, 0x35, 0x45, 0xac, 0x6a, 0x07,
	0xe6, 0x13, 0xb8, 0x8b, 0x2c, 0x4a, 0xfb, 0xb5, 0x02, 0xc8, 0x2f, 0x59, 0xcf, 0x28, 0xd6, 0x49,
	0xf8, 0xb6, 0xcf, 0x61, 0xca, 0xbb, 0xda, 0xf4, 0xc8, 0x4b, 0x32, 0x70, 0x39, 0xd1, 0x83, 0x34,
	0x77, 0x56, 0xd6, 0x98, 0xf4, 0x08, 0x3b, 0x01, 0x1e, 0x7d, 0x04, 0x13, 0x23, 0x4c, 0xf7, 0x49,
	0x98, 0xe3, 0xce, 0xce, 0x01, 0x01, 0x16, 0xdd, 0x07, 0x85, 0x71, 0xdb, 0xe9, 0x99, 0x36, 0x63,
	0x41, 0x86, 0x5b, 0x4c, 0x11, 0x9f, 0x98, 0x36, 0xe6, 0x3e, 0xaf, 0xea, 0xa1, 0xbf, 0xb2, 0x19,
	0x43, 0x8f, 0xa0, 0x46, 0x2c, 0x4e, 0x0f, 0x7b, 0x0e, 0x35, 0x06, 0x61, 0x92, 0x3b, 0x93, 0x0b,
	0x02, 0xbf, 0xeb, 0xc1, 0xd1, 0x03, 0x00, 0xf2, 0xd2, 0xe0, 0x01, 0x79, 0xe2, 0x7c, 0xb2, 0xe2,
	0xc1, 0x7d, 0xae, 0x0a, 0xe1, 0xf5, 0x50, 0xd8, 0xa5, 0xdc, 0x0d, 0x1f, 0xd1, 0xa7, 0x50, 0x3d,
	0x70, 0xb1, 0xc5, 0x0d, 0x7e, 0xa8, 0x56, 0x73, 0x6c, 0x26, 0x04, 0xa3, 0x4f, 0xa0, 0x62, 0xbb,
	0x7c, 0x60, 0x8f, 0x88, 0xaa, 0xe4, 0xf8, 0x7a, 0x21, 0x18, 0x3d, 0x00, 0x45, 0x37, 0x28, 0x19,
	0x08, 0xef, 0x42, 0x9e, 0xc2, 0x14, 0xc1, 0xd1, 0x0e, 0xd4, 0xfb, 0x98, 0x91, 0x9e, 0x61, 0x31,
	0x4e, 0xdd, 0x11, 0xb1, 0xb8, 0x5a, 0xcb, 0x11, 0x61, 0xda, 0x23, 0x7d, 0x19, 0x71, 0xd0, 0x17,
	0x30, 0x73, 0xe0, 0xda, 0x3c, 0x16, 0x67, 0x32, 0x47, 0x9c, 0xba, 0x60, 0x49, 0x81, 0x1e, 0x41,
	0x8d, 0xe3, 0x7d, 0xd2, 0x73, 0xa8, 0xfd, 0xc2, 0xe0, 0xea, 0x54, 0x0e, 0x41, 0x3d, 0xfc, 0xae,
	0x80, 0xa3, 0xfb, 0x50, 0x1d, 0xd8, 0x23, 0x2f, 0x10, 0x53, 0xa7, 0x73, 0xbc, 0x3e, 0x42, 0x7b,
	0x4c, 0xc6, 0x29, 0xe6, 0x64, 0x78, 0xa8, 0xd6, 0xf3, 0x30, 0x43, 0x34, 0x7a, 0x08, 0x35, 0xe1,
	0x99, 0x81, 0x69, 0x33, 0xa2, 0xab, 0x33, 0xe7, 0x3a, 0x06, 0x3c, 0xf8, 0x96, 0x40, 0x27, 0xee,
	0x05, 0xb7, 0xfe, 0xc1, 0xbd, 0x40, 0xdb, 0x87, 0xd9, 0x98, 0x83, 0x2f, 0x94, 0x9c, 0x56, 0x63,
	0xc9, 0x09, 0x45, 0xc9, 0x49, 0xc4, 0x94, 0x4a, 0xe0, 0x5f, 0x65, 0x50, 0xa2, 0xb1, 0x54, 0x11,
	0xbc, 0x74, 0xda, 0x58, 0x88, 0xa5, 0x0d, 0x25, 0x4a, 0x0c, 0x8b, 0xc9, 0xc4, 0x50, 0x94, 0xbc,
	0xdf, 0x4a, 0x7b, 0xbf, 0x18, 0xb3, 0xf7, 0x72, 0xca, 0xde, 0xc5, 0x7c, 0x0e, 0x6e, 0x24, 0x1c,
	0x5c, 0x94, 0x4c, 0xaa, 0xc6, 0x4d, 0xaa, 0x9c, 0xda, 0x70, 0x29, 0x69, 0x43, 0x45, 0x36, 0xda,
	0x9d, 0x6c, 0xa3, 0x29, 0x29, 0x2b, 0xdd, 0x1d, 0x63, 0x25, 0x25, 0x6d, 0x96, 0x56, 0xda, 0x2c,
	0xc5, 0x98, 0x1f, 0x1a, 0x09, 0x3f, 0x28, 0xd2, 0x89, 0x6f, 0x24, 0x4e, 0xbc, 0xf2, 0x16, 0x9c,
	0xe9, 0xd7, 0x15, 0x98, 0xf1, 0xee, 0x60, 0xb1, 0xa2, 0xf4, 0xaf, 0x9f, 0xb6, 0xeb, 0x22, 0x75,
	0x5d, 0xa4, 0xae, 0x8b, 0xd4, 0x7f, 0x62, 0x68, 0x03, 0x6e, 0x49, 0x7e, 0xbe, 0xd2, 0x12, 0xf5,
	0x1e, 0xcc, 0x06, 0xf7, 0xf5, 0xb3, 0xb2, 0x87, 0x66, 0xc2, 0x5c, 0x1c, 0x76, 0xa5, 0x8b, 0xba,
	0x0d, 0xc8, 0xbf, 0xae, 0x67, 0xae, 0x29, 0xbc, 0xd4, 0x6f, 0xc1, 0x6c, 0x0c, 0x75, 0x91, 0x25,
	0xdd, 0xfb, 0xe3, 0x26, 0x4c, 0x07, 0x4d, 0xc1, 0x1e, 0xa1, 0x3f, 0x78, 0xf6, 0xdf, 0x85, 0xa9,
	0xd8, 0xff, 0x52, 0x68, 0x39, 0x5a, 0x68, 0xd6, 0xdf, 0x8b, 0x8d, 0xe6, 0xb8, 0x69, 0x7f, 0x41,
	0x5a, 0xc1, 0x8b, 0x18, 0x6b, 0x3f, 0xa4, 0x88, 0x59, 0xed, 0x8b, 0x14, 0x31, 0xb3, 0x6b, 0xd1,
	0x0a, 0xe8, 0x29, 0xd4, 0xa4, 0xae, 0x1b, 0x2d, 0x66, 0xf5, 0xe2, 0x61, 0xb4, 0xa5, 0xec, 0xc9,
	0x28, 0xd6, 0x73, 0xa8, 0x27, 0x5a, 0x49, 0xd4, 0x8a, 0x28, 0xd9, 0xed, 0x67, 0x63, 0x65, 0x3c,
	0x20, 0x8a, 0xbb, 0x07, 0xd3, 0xf1, 0x56, 0x10, 0x35, 0x63, 0xac, 0x54, 0x33, 0xd9, 0x68, 0x8d,
	0x9d, 0x97, 0x37, 0x2e, 0xdd, 0xdf, 0xa4, 0x8d, 0xa7, 0xfb, 0x32, 0x69, 0xe3, 0x19, 0x57, 0x3e,
	0xad, 0x80, 0xb6, 0x41, 0x89, 0x6c, 0x86, 0xde, 0x8d, 0x7d, 0xa5, 0x58, 0x9c, 0x46, 0xd6, 0x54,
	0x14, 0xe5, 0x6b, 0x98, 0x94, 0xad, 0x81, 0x96, 0x92, 0x9b, 0x88, 0xc5, 0x5a, 0x1e, 0x33, 0x2b,
	0x6f, 0x50, 0x3a, 0xd5, 0xd2, 0x06, 0xd3, 0x8e, 0x90, 0x36, 0x98, 0x61, 0x04, 0xad, 0xb0, 0xb9,
	0xfc, 0xea, 0xb8, 0x59, 0xf8, 0xfd, 0xb8, 0x59, 0xf8, 0xf3, 0xb8, 0x59, 0xf8, 0xe9, 0x4d, 0xb3,
	0xf0, 0xea, 0x4d, 0xb3, 0xf0, 0x6d, 0xa5, 0xe3, 0xff, 0x6f, 0xdf, 0x9f, 0x10, 0x59, 0xe8, 0xc3,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x84, 0xab, 0x22, 0x8a, 0xc8, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JournalServiceClient is the client API for JournalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JournalServiceClient interface {
	CreateJournal(ctx context.Context, in *CreateJournalRequest, opts ...grpc.CallOption) (*CreateJournalResponse, error)
	DeleteJournal(ctx context.Context, in *DeleteJournalRequest, opts ...grpc.CallOption) (*DeleteJournalResponse, error)
	EditJournal(ctx context.Context, in *EditJournalRequest, opts ...grpc.CallOption) (*EditJournalResponse, error)
	FindAllJournals(ctx context.Context, in *FindAllJournalsRequest, opts ...grpc.CallOption) (*FindAllJournalsResponse, error)
	FindOneJournal(ctx context.Context, in *FindOneJournalRequest, opts ...grpc.CallOption) (*FindOneJournalResponse, error)
	CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeResponse, error)
	EditTrade(ctx context.Context, in *EditTradeRequest, opts ...grpc.CallOption) (*EditTradeResponse, error)
	FindOneTrade(ctx context.Context, in *FindOneTradeRequest, opts ...grpc.CallOption) (*FindOneTradeResponse, error)
	DeleteTrade(ctx context.Context, in *DeleteTradeRequest, opts ...grpc.CallOption) (*DeleteTradeResponse, error)
}

type journalServiceClient struct {
	cc *grpc.ClientConn
}

func NewJournalServiceClient(cc *grpc.ClientConn) JournalServiceClient {
	return &journalServiceClient{cc}
}

func (c *journalServiceClient) CreateJournal(ctx context.Context, in *CreateJournalRequest, opts ...grpc.CallOption) (*CreateJournalResponse, error) {
	out := new(CreateJournalResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/CreateJournal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalServiceClient) DeleteJournal(ctx context.Context, in *DeleteJournalRequest, opts ...grpc.CallOption) (*DeleteJournalResponse, error) {
	out := new(DeleteJournalResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/DeleteJournal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalServiceClient) EditJournal(ctx context.Context, in *EditJournalRequest, opts ...grpc.CallOption) (*EditJournalResponse, error) {
	out := new(EditJournalResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/EditJournal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalServiceClient) FindAllJournals(ctx context.Context, in *FindAllJournalsRequest, opts ...grpc.CallOption) (*FindAllJournalsResponse, error) {
	out := new(FindAllJournalsResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/FindAllJournals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalServiceClient) FindOneJournal(ctx context.Context, in *FindOneJournalRequest, opts ...grpc.CallOption) (*FindOneJournalResponse, error) {
	out := new(FindOneJournalResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/FindOneJournal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalServiceClient) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeResponse, error) {
	out := new(CreateTradeResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/CreateTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalServiceClient) EditTrade(ctx context.Context, in *EditTradeRequest, opts ...grpc.CallOption) (*EditTradeResponse, error) {
	out := new(EditTradeResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/EditTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalServiceClient) FindOneTrade(ctx context.Context, in *FindOneTradeRequest, opts ...grpc.CallOption) (*FindOneTradeResponse, error) {
	out := new(FindOneTradeResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/FindOneTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalServiceClient) DeleteTrade(ctx context.Context, in *DeleteTradeRequest, opts ...grpc.CallOption) (*DeleteTradeResponse, error) {
	out := new(DeleteTradeResponse)
	err := c.cc.Invoke(ctx, "/journal.JournalService/DeleteTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JournalServiceServer is the server API for JournalService service.
type JournalServiceServer interface {
	CreateJournal(context.Context, *CreateJournalRequest) (*CreateJournalResponse, error)
	DeleteJournal(context.Context, *DeleteJournalRequest) (*DeleteJournalResponse, error)
	EditJournal(context.Context, *EditJournalRequest) (*EditJournalResponse, error)
	FindAllJournals(context.Context, *FindAllJournalsRequest) (*FindAllJournalsResponse, error)
	FindOneJournal(context.Context, *FindOneJournalRequest) (*FindOneJournalResponse, error)
	CreateTrade(context.Context, *CreateTradeRequest) (*CreateTradeResponse, error)
	EditTrade(context.Context, *EditTradeRequest) (*EditTradeResponse, error)
	FindOneTrade(context.Context, *FindOneTradeRequest) (*FindOneTradeResponse, error)
	DeleteTrade(context.Context, *DeleteTradeRequest) (*DeleteTradeResponse, error)
}

// UnimplementedJournalServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJournalServiceServer struct {
}

func (*UnimplementedJournalServiceServer) CreateJournal(ctx context.Context, req *CreateJournalRequest) (*CreateJournalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJournal not implemented")
}
func (*UnimplementedJournalServiceServer) DeleteJournal(ctx context.Context, req *DeleteJournalRequest) (*DeleteJournalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJournal not implemented")
}
func (*UnimplementedJournalServiceServer) EditJournal(ctx context.Context, req *EditJournalRequest) (*EditJournalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditJournal not implemented")
}
func (*UnimplementedJournalServiceServer) FindAllJournals(ctx context.Context, req *FindAllJournalsRequest) (*FindAllJournalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllJournals not implemented")
}
func (*UnimplementedJournalServiceServer) FindOneJournal(ctx context.Context, req *FindOneJournalRequest) (*FindOneJournalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOneJournal not implemented")
}
func (*UnimplementedJournalServiceServer) CreateTrade(ctx context.Context, req *CreateTradeRequest) (*CreateTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrade not implemented")
}
func (*UnimplementedJournalServiceServer) EditTrade(ctx context.Context, req *EditTradeRequest) (*EditTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTrade not implemented")
}
func (*UnimplementedJournalServiceServer) FindOneTrade(ctx context.Context, req *FindOneTradeRequest) (*FindOneTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOneTrade not implemented")
}
func (*UnimplementedJournalServiceServer) DeleteTrade(ctx context.Context, req *DeleteTradeRequest) (*DeleteTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrade not implemented")
}

func RegisterJournalServiceServer(s *grpc.Server, srv JournalServiceServer) {
	s.RegisterService(&_JournalService_serviceDesc, srv)
}

func _JournalService_CreateJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).CreateJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/CreateJournal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).CreateJournal(ctx, req.(*CreateJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalService_DeleteJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).DeleteJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/DeleteJournal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).DeleteJournal(ctx, req.(*DeleteJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalService_EditJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).EditJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/EditJournal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).EditJournal(ctx, req.(*EditJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalService_FindAllJournals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllJournalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).FindAllJournals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/FindAllJournals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).FindAllJournals(ctx, req.(*FindAllJournalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalService_FindOneJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).FindOneJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/FindOneJournal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).FindOneJournal(ctx, req.(*FindOneJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalService_CreateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).CreateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/CreateTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).CreateTrade(ctx, req.(*CreateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalService_EditTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).EditTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/EditTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).EditTrade(ctx, req.(*EditTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalService_FindOneTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).FindOneTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/FindOneTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).FindOneTrade(ctx, req.(*FindOneTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalService_DeleteTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServiceServer).DeleteTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journal.JournalService/DeleteTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServiceServer).DeleteTrade(ctx, req.(*DeleteTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JournalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "journal.JournalService",
	HandlerType: (*JournalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJournal",
			Handler:    _JournalService_CreateJournal_Handler,
		},
		{
			MethodName: "DeleteJournal",
			Handler:    _JournalService_DeleteJournal_Handler,
		},
		{
			MethodName: "EditJournal",
			Handler:    _JournalService_EditJournal_Handler,
		},
		{
			MethodName: "FindAllJournals",
			Handler:    _JournalService_FindAllJournals_Handler,
		},
		{
			MethodName: "FindOneJournal",
			Handler:    _JournalService_FindOneJournal_Handler,
		},
		{
			MethodName: "CreateTrade",
			Handler:    _JournalService_CreateTrade_Handler,
		},
		{
			MethodName: "EditTrade",
			Handler:    _JournalService_EditTrade_Handler,
		},
		{
			MethodName: "FindOneTrade",
			Handler:    _JournalService_FindOneTrade_Handler,
		},
		{
			MethodName: "DeleteTrade",
			Handler:    _JournalService_DeleteTrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/journal.proto",
}
