# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helper_pb2 as helper__pb2


class STHelperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeFinancialData = channel.unary_unary(
                '/helper.STHelper/AnalyzeFinancialData',
                request_serializer=helper__pb2.FinancialRequest.SerializeToString,
                response_deserializer=helper__pb2.FinancialResponse.FromString,
                )
        self.GetStockQuote = channel.unary_unary(
                '/helper.STHelper/GetStockQuote',
                request_serializer=helper__pb2.StockQuoteRequest.SerializeToString,
                response_deserializer=helper__pb2.StockQuoteResponse.FromString,
                )
        self.GetHistoricalStockData = channel.unary_unary(
                '/helper.STHelper/GetHistoricalStockData',
                request_serializer=helper__pb2.HistoricalStockDataRequest.SerializeToString,
                response_deserializer=helper__pb2.HistoricalStockDataResponse.FromString,
                )


class STHelperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeFinancialData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalStockData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STHelperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeFinancialData': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFinancialData,
                    request_deserializer=helper__pb2.FinancialRequest.FromString,
                    response_serializer=helper__pb2.FinancialResponse.SerializeToString,
            ),
            'GetStockQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockQuote,
                    request_deserializer=helper__pb2.StockQuoteRequest.FromString,
                    response_serializer=helper__pb2.StockQuoteResponse.SerializeToString,
            ),
            'GetHistoricalStockData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalStockData,
                    request_deserializer=helper__pb2.HistoricalStockDataRequest.FromString,
                    response_serializer=helper__pb2.HistoricalStockDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helper.STHelper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class STHelper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeFinancialData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helper.STHelper/AnalyzeFinancialData',
            helper__pb2.FinancialRequest.SerializeToString,
            helper__pb2.FinancialResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStockQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helper.STHelper/GetStockQuote',
            helper__pb2.StockQuoteRequest.SerializeToString,
            helper__pb2.StockQuoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHistoricalStockData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helper.STHelper/GetHistoricalStockData',
            helper__pb2.HistoricalStockDataRequest.SerializeToString,
            helper__pb2.HistoricalStockDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
