apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.journalDb.service.name }}
spec:
  ports:
    - port: {{ .Values.journalDb.service.port }}
      targetPort: {{ .Values.journalDb.deployment.port }}
  selector:
    app: {{ .Values.journalDb.deployment.name }}
