apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app.label }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: metrics
      port: 9092
      targetPort: 9092
  type: LoadBalancer
