apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME_PLACEHOLDER
spec:
  selector:
    app: APP_LABEL_PLACEHOLDER
  ports:
    - protocol: TCP
      port: SERVICE_PORT_PLACEHOLDER
      targetPort: CONTAINER_PORT_PLACEHOLDER
  type: LoadBalancer