// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/pb/auth.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteUserRequest struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{0}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteUserResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{1}
}
func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoginRequest struct {
	Email                *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() *wrapperspb.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *LoginRequest) GetPassword() *wrapperspb.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

type LoginResponse struct {
	Status               uint64     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *LoginData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{3}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoginResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LoginResponse) GetData() *LoginData {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginData) Reset()         { *m = LoginData{} }
func (m *LoginData) String() string { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()    {}
func (*LoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{4}
}
func (m *LoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginData.Unmarshal(m, b)
}
func (m *LoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginData.Marshal(b, m, deterministic)
}
func (m *LoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginData.Merge(m, src)
}
func (m *LoginData) XXX_Size() int {
	return xxx_messageInfo_LoginData.Size(m)
}
func (m *LoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginData proto.InternalMessageInfo

func (m *LoginData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginData) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *LoginData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RegisterRequest struct {
	Email                *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role                 *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{5}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() *wrapperspb.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *RegisterRequest) GetPassword() *wrapperspb.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *RegisterRequest) GetFirstName() *wrapperspb.StringValue {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *RegisterRequest) GetLastName() *wrapperspb.StringValue {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *RegisterRequest) GetRole() *wrapperspb.StringValue {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *RegisterRequest) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type RegisterResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{6}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RegisterResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RegisterResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

// Find Users
type FindOneUserRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneUserRequest) Reset()         { *m = FindOneUserRequest{} }
func (m *FindOneUserRequest) String() string { return proto.CompactTextString(m) }
func (*FindOneUserRequest) ProtoMessage()    {}
func (*FindOneUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{7}
}
func (m *FindOneUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneUserRequest.Unmarshal(m, b)
}
func (m *FindOneUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneUserRequest.Marshal(b, m, deterministic)
}
func (m *FindOneUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneUserRequest.Merge(m, src)
}
func (m *FindOneUserRequest) XXX_Size() int {
	return xxx_messageInfo_FindOneUserRequest.Size(m)
}
func (m *FindOneUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneUserRequest proto.InternalMessageInfo

func (m *FindOneUserRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindOneUserResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneUserResponse) Reset()         { *m = FindOneUserResponse{} }
func (m *FindOneUserResponse) String() string { return proto.CompactTextString(m) }
func (*FindOneUserResponse) ProtoMessage()    {}
func (*FindOneUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{8}
}
func (m *FindOneUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneUserResponse.Unmarshal(m, b)
}
func (m *FindOneUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneUserResponse.Marshal(b, m, deterministic)
}
func (m *FindOneUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneUserResponse.Merge(m, src)
}
func (m *FindOneUserResponse) XXX_Size() int {
	return xxx_messageInfo_FindOneUserResponse.Size(m)
}
func (m *FindOneUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneUserResponse proto.InternalMessageInfo

func (m *FindOneUserResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FindOneUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FindOneUserResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

// Find All Users
type FindAllUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllUsersRequest) Reset()         { *m = FindAllUsersRequest{} }
func (m *FindAllUsersRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllUsersRequest) ProtoMessage()    {}
func (*FindAllUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{9}
}
func (m *FindAllUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllUsersRequest.Unmarshal(m, b)
}
func (m *FindAllUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllUsersRequest.Marshal(b, m, deterministic)
}
func (m *FindAllUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllUsersRequest.Merge(m, src)
}
func (m *FindAllUsersRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllUsersRequest.Size(m)
}
func (m *FindAllUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllUsersRequest proto.InternalMessageInfo

type FindAllUsersResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*User  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllUsersResponse) Reset()         { *m = FindAllUsersResponse{} }
func (m *FindAllUsersResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllUsersResponse) ProtoMessage()    {}
func (*FindAllUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{10}
}
func (m *FindAllUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllUsersResponse.Unmarshal(m, b)
}
func (m *FindAllUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllUsersResponse.Marshal(b, m, deterministic)
}
func (m *FindAllUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllUsersResponse.Merge(m, src)
}
func (m *FindAllUsersResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllUsersResponse.Size(m)
}
func (m *FindAllUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllUsersResponse proto.InternalMessageInfo

func (m *FindAllUsersResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FindAllUsersResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FindAllUsersResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateUserRequest struct {
	Email                *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role                 *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Id                   uint64                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{11}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetEmail() *wrapperspb.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *UpdateUserRequest) GetPassword() *wrapperspb.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *UpdateUserRequest) GetFirstName() *wrapperspb.StringValue {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *UpdateUserRequest) GetLastName() *wrapperspb.StringValue {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *UpdateUserRequest) GetRole() *wrapperspb.StringValue {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *UpdateUserRequest) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UpdateUserRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateUserResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{12}
}
func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateUserResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type ValidateRequest struct {
	Token                *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{13}
}
func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetToken() *wrapperspb.StringValue {
	if m != nil {
		return m.Token
	}
	return nil
}

type ValidateResponse struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UserId               uint64   `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{14}
}
func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ValidateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ValidateResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type User struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"firstName"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"lastName"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Token                string   `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_329ec36c14ab2ce3, []int{15}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteUserRequest)(nil), "auth.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "auth.DeleteUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*LoginData)(nil), "auth.LoginData")
	proto.RegisterType((*RegisterRequest)(nil), "auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "auth.RegisterResponse")
	proto.RegisterType((*FindOneUserRequest)(nil), "auth.FindOneUserRequest")
	proto.RegisterType((*FindOneUserResponse)(nil), "auth.FindOneUserResponse")
	proto.RegisterType((*FindAllUsersRequest)(nil), "auth.FindAllUsersRequest")
	proto.RegisterType((*FindAllUsersResponse)(nil), "auth.FindAllUsersResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "auth.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "auth.UpdateUserResponse")
	proto.RegisterType((*ValidateRequest)(nil), "auth.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "auth.ValidateResponse")
	proto.RegisterType((*User)(nil), "auth.User")
}

func init() { proto.RegisterFile("pkg/pb/auth.proto", fileDescriptor_329ec36c14ab2ce3) }

var fileDescriptor_329ec36c14ab2ce3 = []byte{
	// 786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4b, 0x4f, 0xdb, 0x4e,
	0x10, 0xcf, 0x9b, 0x78, 0x80, 0x3f, 0xb0, 0x3c, 0xfe, 0xc1, 0xaa, 0x0c, 0x32, 0x3d, 0x50, 0x89,
	0x26, 0x55, 0x7a, 0x29, 0xe2, 0x50, 0x05, 0x41, 0xab, 0x4a, 0x7d, 0x48, 0xa6, 0xa0, 0xaa, 0x17,
	0xba, 0x89, 0x17, 0x63, 0xe1, 0xd8, 0xae, 0x77, 0x5d, 0x2e, 0xfd, 0x12, 0xbd, 0xf5, 0x23, 0x71,
	0xec, 0x27, 0x40, 0x15, 0xf4, 0xc4, 0x07, 0xa8, 0xd4, 0x5b, 0xe5, 0x5d, 0xaf, 0x1f, 0x49, 0x54,
	0x50, 0x5a, 0x7a, 0xea, 0xcd, 0x3b, 0xf3, 0x9b, 0x47, 0x66, 0x7e, 0x33, 0x13, 0x98, 0xf3, 0x4f,
	0xac, 0x96, 0xdf, 0x6d, 0xe1, 0x90, 0x1d, 0x37, 0xfd, 0xc0, 0x63, 0x1e, 0xaa, 0x44, 0xdf, 0xea,
	0x8a, 0xe5, 0x79, 0x96, 0x43, 0x5a, 0x5c, 0xd6, 0x0d, 0x8f, 0x5a, 0xcc, 0xee, 0x13, 0xca, 0x70,
	0xdf, 0x17, 0x30, 0x55, 0x1b, 0x04, 0x9c, 0x06, 0xd8, 0xf7, 0x49, 0x40, 0x63, 0xfd, 0x7d, 0xcb,
	0x66, 0xc7, 0x61, 0xb7, 0xd9, 0xf3, 0xfa, 0x2d, 0xcb, 0xb3, 0xbc, 0x14, 0x18, 0xbd, 0xf8, 0x83,
	0x7f, 0x09, 0xb8, 0xbe, 0x06, 0x73, 0x3b, 0xc4, 0x21, 0x8c, 0xec, 0x53, 0x12, 0x18, 0xe4, 0x7d,
	0x48, 0x28, 0x43, 0xff, 0x41, 0xc9, 0x36, 0x1b, 0xc5, 0xd5, 0xf2, 0xba, 0x62, 0x94, 0x6c, 0x53,
	0xdf, 0x06, 0x94, 0x05, 0x51, 0xdf, 0x73, 0x29, 0x41, 0x4b, 0x50, 0xa3, 0x0c, 0xb3, 0x90, 0x36,
	0x8a, 0xab, 0xc5, 0xf5, 0x8a, 0x11, 0xbf, 0xd0, 0x02, 0x54, 0x49, 0x10, 0x78, 0x41, 0xa3, 0xb4,
	0x5a, 0x5c, 0x57, 0x0c, 0xf1, 0xd0, 0x3f, 0xc2, 0xd4, 0x73, 0xcf, 0xb2, 0x5d, 0x19, 0xa3, 0x0d,
	0x55, 0xd2, 0xc7, 0xb6, 0xc3, 0x8d, 0x27, 0xdb, 0x77, 0x9a, 0xe2, 0x77, 0x35, 0x65, 0xba, 0xcd,
	0x3d, 0x16, 0xd8, 0xae, 0x75, 0x80, 0x9d, 0x90, 0x18, 0x02, 0x8a, 0x1e, 0x41, 0xdd, 0xc7, 0x94,
	0x9e, 0x7a, 0x81, 0xc9, 0x9d, 0x5f, 0x67, 0x96, 0xa0, 0xf5, 0x2e, 0x4c, 0xc7, 0xd1, 0xc7, 0x49,
	0x1e, 0xad, 0x41, 0xc5, 0xc4, 0x0c, 0x37, 0xca, 0x3c, 0xe8, 0x4c, 0x93, 0xb7, 0x8d, 0x3b, 0xdc,
	0xc1, 0x0c, 0x1b, 0x5c, 0xa9, 0xef, 0x82, 0x92, 0x88, 0x22, 0x3f, 0xcc, 0x3b, 0x21, 0x2e, 0x77,
	0xaf, 0x18, 0xe2, 0x81, 0x10, 0x54, 0x02, 0xcf, 0x21, 0xb1, 0x73, 0xfe, 0x1d, 0x17, 0xbb, 0xcc,
	0xb3, 0x88, 0x8a, 0xfd, 0xad, 0x04, 0x33, 0x06, 0xb1, 0x6c, 0xca, 0xd2, 0x86, 0xfc, 0xd5, 0x62,
	0xa1, 0x2d, 0x80, 0x23, 0x3b, 0xa0, 0xec, 0xd0, 0xc5, 0x7d, 0x12, 0xff, 0xe6, 0x5f, 0xdb, 0x2a,
	0x1c, 0xff, 0x12, 0xf7, 0x09, 0xda, 0x04, 0xc5, 0xc1, 0xd2, 0xb6, 0x72, 0x93, 0xb8, 0x11, 0x9c,
	0x9b, 0x3e, 0x88, 0xab, 0x53, 0xbd, 0x81, 0x95, 0xa8, 0xdd, 0x26, 0x40, 0x2f, 0x20, 0x98, 0x11,
	0xf3, 0x10, 0xb3, 0x46, 0x8d, 0xdb, 0xa9, 0x43, 0x76, 0xaf, 0xe5, 0x08, 0x19, 0x4a, 0x8c, 0xee,
	0x30, 0xfd, 0x1d, 0xcc, 0xa6, 0x55, 0x1e, 0x8b, 0x14, 0x5a, 0x8e, 0x14, 0x20, 0x48, 0xc1, 0x27,
	0x44, 0xf0, 0xe1, 0x2e, 0xa0, 0x27, 0xb6, 0x6b, 0xbe, 0x72, 0x47, 0xce, 0x96, 0x6c, 0x77, 0x0f,
	0xe6, 0x73, 0xa8, 0x5b, 0x49, 0x65, 0x51, 0x04, 0xe9, 0x38, 0x4e, 0x24, 0xa4, 0x71, 0x2e, 0xba,
	0x09, 0x0b, 0x79, 0xf1, 0x6f, 0x06, 0x2f, 0x8f, 0x0c, 0xfe, 0xbd, 0x04, 0x73, 0xfb, 0xbe, 0x89,
	0xf3, 0x3b, 0xe6, 0x1f, 0xa5, 0xff, 0x34, 0xa5, 0x63, 0x6a, 0x4d, 0x24, 0xd4, 0xea, 0x02, 0xca,
	0xd6, 0xfd, 0x56, 0x98, 0xb5, 0x0b, 0x33, 0x07, 0xd8, 0xb1, 0xa3, 0x28, 0x99, 0xce, 0xa6, 0xab,
	0xef, 0xda, 0xce, 0x72, 0xa8, 0xfe, 0x06, 0x66, 0x53, 0x37, 0x63, 0x25, 0xba, 0x04, 0xb5, 0x90,
	0x92, 0xe0, 0x99, 0x5c, 0xa5, 0xf1, 0x4b, 0xff, 0x51, 0x84, 0x4a, 0x94, 0xef, 0xe0, 0xe0, 0x71,
	0x37, 0x9c, 0x80, 0xd2, 0x0d, 0xa7, 0x98, 0x9a, 0xa1, 0x58, 0x99, 0x2b, 0x52, 0x12, 0x6d, 0xe4,
	0x48, 0x14, 0x11, 0x41, 0xd9, 0x9e, 0xbe, 0x3a, 0x5f, 0x49, 0xa9, 0x92, 0x65, 0xcd, 0xbd, 0x2c,
	0x6b, 0xaa, 0x1c, 0x3c, 0x75, 0x75, 0xbe, 0x92, 0x70, 0x23, 0xc3, 0x12, 0x79, 0x16, 0x6a, 0x99,
	0xb3, 0x90, 0x1c, 0x90, 0x89, 0xec, 0x01, 0xd9, 0xc8, 0xb1, 0xa3, 0x9e, 0xa6, 0x90, 0xb0, 0x20,
	0x43, 0x88, 0xf6, 0xa7, 0x0a, 0x4c, 0x76, 0x42, 0x76, 0xbc, 0x47, 0x82, 0x0f, 0x76, 0x8f, 0xa0,
	0x0e, 0x40, 0x7a, 0xc7, 0xd1, 0xff, 0xa2, 0x99, 0x43, 0xe7, 0x5f, 0x6d, 0x0c, 0x2b, 0x44, 0x4b,
	0xf4, 0x02, 0x7a, 0x0a, 0x53, 0xd9, 0x95, 0x81, 0x96, 0x05, 0x76, 0xc4, 0x76, 0x51, 0xd5, 0x51,
	0xaa, 0xc4, 0xd1, 0x63, 0xa8, 0x45, 0x9a, 0x17, 0x04, 0x35, 0x52, 0x5c, 0x7e, 0x57, 0xaa, 0xcb,
	0x23, 0x34, 0x89, 0x83, 0x1d, 0x98, 0xcc, 0x28, 0xc6, 0xf5, 0xd2, 0x86, 0x2a, 0x3f, 0xda, 0x08,
	0x65, 0x8e, 0xba, 0xb4, 0x9c, 0xcf, 0xc9, 0x12, 0x9b, 0x2d, 0xa8, 0xcb, 0xd3, 0x81, 0x16, 0x05,
	0x64, 0xe0, 0x60, 0xab, 0x4b, 0x83, 0xe2, 0xc4, 0xb8, 0x03, 0x90, 0x0e, 0xa5, 0xec, 0xc1, 0xd0,
	0x7a, 0x94, 0x3d, 0x18, 0x9e, 0x5f, 0x11, 0x5f, 0x0e, 0x8b, 0x8c, 0x3f, 0x30, 0x83, 0x32, 0xfe,
	0xe0, 0x4c, 0xe9, 0x85, 0x6d, 0xed, 0xec, 0x42, 0x2b, 0x7c, 0xb9, 0xd0, 0x0a, 0x5f, 0x2f, 0xb4,
	0xc2, 0xe7, 0x4b, 0xad, 0x70, 0x76, 0xa9, 0x15, 0xde, 0xd6, 0x9b, 0x2d, 0xf1, 0x8f, 0xb4, 0x5b,
	0xe3, 0x63, 0xfa, 0xf0, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x38, 0x7b, 0xff, 0xa2, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	FindAllUsers(ctx context.Context, in *FindAllUsersRequest, opts ...grpc.CallOption) (*FindAllUsersResponse, error)
	FindMe(ctx context.Context, in *FindOneUserRequest, opts ...grpc.CallOption) (*FindOneUserResponse, error)
	FindOneUser(ctx context.Context, in *FindOneUserRequest, opts ...grpc.CallOption) (*FindOneUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) FindAllUsers(ctx context.Context, in *FindAllUsersRequest, opts ...grpc.CallOption) (*FindAllUsersResponse, error) {
	out := new(FindAllUsersResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/FindAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) FindMe(ctx context.Context, in *FindOneUserRequest, opts ...grpc.CallOption) (*FindOneUserResponse, error) {
	out := new(FindOneUserResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/FindMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) FindOneUser(ctx context.Context, in *FindOneUserRequest, opts ...grpc.CallOption) (*FindOneUserResponse, error) {
	out := new(FindOneUserResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/FindOneUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	FindAllUsers(context.Context, *FindAllUsersRequest) (*FindAllUsersResponse, error)
	FindMe(context.Context, *FindOneUserRequest) (*FindOneUserResponse, error)
	FindOneUser(context.Context, *FindOneUserRequest) (*FindOneUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedAuthServiceServer) FindAllUsers(ctx context.Context, req *FindAllUsersRequest) (*FindAllUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllUsers not implemented")
}
func (*UnimplementedAuthServiceServer) FindMe(ctx context.Context, req *FindOneUserRequest) (*FindOneUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMe not implemented")
}
func (*UnimplementedAuthServiceServer) FindOneUser(ctx context.Context, req *FindOneUserRequest) (*FindOneUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOneUser not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAuthServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedAuthServiceServer) Validate(ctx context.Context, req *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_FindAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).FindAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/FindAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).FindAllUsers(ctx, req.(*FindAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_FindMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).FindMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/FindMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).FindMe(ctx, req.(*FindOneUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_FindOneUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).FindOneUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/FindOneUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).FindOneUser(ctx, req.(*FindOneUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteUser",
			Handler:    _AuthService_DeleteUser_Handler,
		},
		{
			MethodName: "FindAllUsers",
			Handler:    _AuthService_FindAllUsers_Handler,
		},
		{
			MethodName: "FindMe",
			Handler:    _AuthService_FindMe_Handler,
		},
		{
			MethodName: "FindOneUser",
			Handler:    _AuthService_FindOneUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _AuthService_UpdateUser_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _AuthService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/auth.proto",
}
